include:
  - board: nice_nano
    shield: charybdis_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: seeeduino_xiao
    shield: charybdis_dongle_prospector prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano
    shield: charybdis_left
  - board: nice_nano
    shield: charybdis_right
    # snippet: zmk-usb-logging
    # cmake-args: -DCONFIG_ZMK_USB_LOGGING=y

  - board: nice_nano
    shield: charybdis_dongle_dual dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: seeeduino_xiao
    shield: charybdis_dongle_dual_prospector prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano
    shield: charybdis_left_dual
  - board: nice_nano
    shield: charybdis_right_dual

  - board: nice_nano
    shield: settings_reset
  - shield: settings_reset
    board: seeeduino_xiao
